### ISSUE TITLE
validator spider是否需要更多的验证

### ISSUE THREAD

**Issue by putaotao** [awolfly9/IPProxyTool#11]
amazon.cn 经常用代理可以访问，但是回来的内容是 "输入验证码" 的页面，这种情况对代理的筛选需要对内容进行验证

**Comment by awolfly9** [comment]
@putaotao 因为我们现在用的都是万人骑的 IP 所以这个 IP 可能被 amazon.cn  列入了嫌疑名单，所以出现了验证码
这种情况，可以在项目中有一个参数变量，检测成功的标识，具体名称是：success_mark 每一个验证的 spider 都有这个变量，具体的修改这个变量，就能够验证不需要输入验证码的 IP
祝解决问题

**Comment by putaotao** [comment]
我看到success_mark了，我有一个想法是，能不能在validator里定义一个方法代替success_mark，然后所有的validator可以继承这个方法，如果返回是true（默认是true）就证明是可以用的代理，这样的话更加灵活。

**Comment by awolfly9** [comment]
@putaotao 可以的，这样应该还比 success_mark 一个单独的参数更加的灵活，而且方便扩展，我抽时间扩展一下

**Comment by putaotao** [comment]
#12

**Comment by awolfly9** [comment]
@putaotao 赞
