### ISSUE TITLE
我是新手，能有一个完整的安装教程么？

### ISSUE THREAD

**Issue by 973204** [awolfly9/IPProxyTool#13]
搞了个搬瓦工的VPS，就是装不上去！

**Comment by 973204** [comment]
PYTHON的版本是2.6.6

**Comment by putaotao** [comment]
你是怎么装的，有什么报错信息吗？

**Comment by awolfly9** [comment]
目前用的 python3.6.1，安装 python3 之后，按照 readme 操作就可以了

**Comment by awolfly9** [comment]
@putaotao https://github.com/awolfly9/IPProxyTool/invitations  邀请你成为协作者

**Comment by Just2co** [comment]
@awolfly9 建议增加SSDB数据库的支持
