### ISSUE TITLE
增加评分，自动验证IP是否有效是不是会好些。

### ISSUE THREAD

**Issue by javmain** [awolfly9/IPProxyTool#18]
如题

**Comment by awolfly9** [comment]
没有增加评分功能，如果验证不过，直接删掉了
原因：
1. 在一堆废墟中增加所谓的评分功能，没有必要
2.在我的测试中，如果一个 IP 一旦失效了，再次有效的概率比较低
3.免费网站能够提供源源不断的 IP

**Comment by Just2co** [comment]
@awolfly9 大神你好，请允许在这里搭车请教个问题，自学python3编程，掌握python语法及相关基础之后，直接从爬虫这里开始，上手难度是不是比直接从Django框架撸WEB后台要容易一些？而且也更加有趣一些？

**Comment by awolfly9** [comment]
@Just2co  你好

关于学习 python 编程，个人认为没有什么特别简单也没有特别难。主要是看你目前的兴趣和目标是什么？

如果你的目标是抓取一些数据统计结果，那么爬虫比较合适，如果你是想搭建一个个人博客，或者提供一些后端 API 那么 django 就比较适合。

以上

**Comment by Just2co** [comment]
@awolfly9 感谢菊苣不吝赐教，我学python首先是兴趣，更重要的是可以转行做软件工程师，实现商业价值！我对比了下从现在正火爆的Java入门，感觉还是python入门更合适，路线也更加清晰，一个月左右的基础学习之后就可以上框架，做小项目了。JAVA的话基础就要两三个月，后面的坑会更多!
