### ISSUE TITLE
持续运行一段时间后表中会有大量重复ip

### ISSUE THREAD

**Issue by MrKang** [awolfly9/IPProxyTool#22]
发现一个问题，如果运行起ipproxypool.py的话，程序会一直跑一直跑，这没啥毛病，但是表里慢慢会出现大量重复的ip，不知道这是出于某种逻辑有意为之还是一个逻辑上的bug？

**Comment by awolfly9** [comment]
你检查下数据库，是否没有设置唯一主键

**Comment by MrKang** [comment]
我用的mongo的啊，我看逻辑其实感觉应该以ip来查询，因为量并不大，性能问题应该可以忽略。ip查更直接

2018-01-19 10:28 GMT+08:00 guangquan <notifications@github.com>:

**Comment by awolfly9** [comment]
mongo 的处理不是特别完善，没有考虑重复问题
