### ISSUE TITLE
Docker启动报错

### ISSUE THREAD

**Issue by SunHuawei** [awolfly9/IPProxyTool#26]
首先要非常感谢作者的无私奉献，这个工具确实非常有用。下面说我的问题。

我在用docker安装的过程中遇到一个问题。
运行`docker build -t proxy .`安装成功没有问题。
运行`docker run -it proxy`报错如下
![image](https://user-images.githubusercontent.com/11191857/38123134-197b7b2a-340c-11e8-94b8-2fb646ac88bb.png)
初步分析是因为`async def`只在`python` 3.5版本以后才支持。目前docker内用到的`docker.io/mrjogo/scrapy`对应的`python`版本是2.7.11。

我想应该修改下镜像，或者镜像里的python版本就好了。不过我不确定scrapy是不是依赖python2。希望有人可以抽出时间帮忙解决该问题。

**Comment by libingtong** [comment]
遇见同样的问题

**Comment by awolfly9** [comment]
@SunHuawei 
整个项目依赖的都是 python3 ，没有在 python2 下测试过兼容性。所以请在 python3 下进行测试。项目开发版本用的是 python3.6.1

**Comment by SunHuawei** [comment]
@awolfly9 , 嗯，我的问题就是不兼容python2，但是Dockerfile里的`FROM docker.io/mrjogo/scrapy`所使用的python版本是2.7。请查看https://hub.docker.com/r/mrjogo/scrapy/。我测试的是master分枝。没有测试docker分枝。

我想解决方案就是替换Dockerfile里的`FROM docker.io/mrjogo/scrapy`成为依赖python3的镜像就好了。就像 @libingtong 所说。

**Comment by SunHuawei** [comment]
@libingtong , 按照你说的换成tarhan/scrapy-base，报这样的一个错
![image](https://user-images.githubusercontent.com/11191857/38131554-22141994-343a-11e8-92b9-59837c1b6de1.png)

**Comment by libingtong** [comment]
@SunHuawei 建立名字是 proxy 的容器后，docker run -it -v /home --name proxy -v /Users/dylan/IPProxyTool:/home tarhan/scrapy-base exit;/bin/bash，然后 cd 到/home下运行。

**Comment by libingtong** [comment]
@SunHuawei 你这样试试：
docker run -it -v /home --name proxy -v ~/IPProxyTool:/home tarhan/python-base sh
然后再安装 scrapy 和requirements.txt的依赖。
