### ISSUE TITLE
Python3下报错

### ISSUE THREAD

**Issue by libingtong** [awolfly9/IPProxyTool#27]
![wx20180331-111423](https://user-images.githubusercontent.com/2126613/38159111-ba7d412a-34d4-11e8-8dd2-9b57b9376cf3.png)

在 macOS 下和 Docker 下，运行 ipproxytool.py 会出现如图中的错误，scrapy已经安装了。
![wx20180331-111754](https://user-images.githubusercontent.com/2126613/38159151-2cb62f7c-34d5-11e8-9c79-ff8692f591a1.png)

**Comment by awolfly9** [comment]
请检查下 scrapy 的安装路径

**Comment by libingtong** [comment]
@awolfly9 scrapy是用 pip install 安装的，是在/usr/local/lib/python3.6/site-packages路径下，看起来是一切正常。

**Comment by libingtong** [comment]
找到问题了，macOS 安装的 Python3 是单独的 python3，所以通过subprocess.Popen打开的进程改成 python3就正常了。
