### ISSUE TITLE
No module named ipproxytool.spiders.proxy.xicidaili

### ISSUE THREAD

**Issue by YouYII** [awolfly9/IPProxyTool#3]
依赖都安装好后 , 执行报错,  python 没用过 , 求助

➜  IPProxyTool git:(master) ✗ python runspider.py
Traceback (most recent call last):
  File "runspider.py", line 12, in <module>
    from ipproxytool.spiders.proxy.xicidaili import XiCiDaiLiSpider
ImportError: No module named ipproxytool.spiders.proxy.xicidaili

**Comment by awolfly9** [comment]
@YouYII 我在测试中并没有出现这种情况，建议你加我微信，详细说明。
