### ISSUE TITLE
关于 server 的性能问题

### ISSUE THREAD

**Issue by Panmax** [awolfly9/IPProxyTool#8]
我看到源码中 server 是用 flask 直接 run 起来的，没有使用任何容器。这样是不是会有性能问题？

其实我在使用中还没碰到过问题，我现在写的程序每秒的请求并发大概是 40 左右，担心将来翻几倍的情况下有性能瓶颈。

**Comment by awolfly9** [comment]
@Panmax 你好，这种情况，客户端可以做缓存的，每次可以请求 10 - 50 个 IP。然后检测到 IP 可用剩余过少时，再次请求。所以性能可以通过这种方式避免的。

抱歉回复完了。

**Comment by Panmax** [comment]
没关系。

如果用本地缓存的方式，本地就需要维护一个可用的 IP 池，这样本地所需要做的工作就增加了。

**Comment by awolfly9** [comment]
@Panmax 是的。我目前采用的方式就是在本地加一个 IP 池。如果你有很好的能够承载高并发请求的处理方式，欢迎提交代码，一起维护。
